# Generated by Django 4.2.6 on 2023-11-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'permissions': [('set_active_status', 'Can activate/deactivate users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
