# Generated by Django 4.2.6 on 2023-11-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'permissions': [('set_user_active_status', 'Can activate/deactivate users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
