# Generated by Django 4.2.6 on 2023-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_rename_mailinglist_schedule_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day of the month to send'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True, verbose_name='Day of the week to send'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('r', 'Running'), ('p', 'Paused'), ('f', 'Completed')], default='c', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(verbose_name='Time to send'),
        ),
    ]
