# Generated by Django 4.2.6 on 2023-11-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_schedule_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-start_date',), 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_last_attempt', models.DateTimeField(auto_now=True, verbose_name='Date and time of last attempt')),
                ('status_of_last_attempt', models.BooleanField(default=False, verbose_name='Status of last attempt')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Server response')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Mailing log',
                'ordering': ('-date_of_last_attempt',),
            },
        ),
    ]
