# Generated by Django 4.2.6 on 2023-11-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='message',
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.schedule', verbose_name='Schedule'),
        ),
    ]
