# Generated by Django 4.2.6 on 2023-11-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_remove_mailinglog_message_mailinglog_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End day'),
        ),
    ]
