# Generated by Django 4.2.6 on 2023-11-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_date',), 'permissions': [('set_published_status', 'Can publish article')], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
